### ISSUE TITLE
数字人连接上了面板，但是没有把对话上传到ue5

### ISSUE THREAD

**Issue by Solenyalyl** [xszyou/Fay#100]
报错：
"POST /api/submit HTTP/1.1" 200 245 0.001000
Exception in thread Thread-14 (__record):
Traceback (most recent call last):
  File "C:\setup\miniconda\install\envs\mubai\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\setup\miniconda\install\envs\mubai\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mubai\Fay-fay-assistant-edition\Fay-fay-assistant-edition\core\recorder.py", line 191, in __record
    data = np.reshape(data, (-1, channels))  # reshaping the array to split the channels
  File "C:\setup\miniconda\install\envs\mubai\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\setup\miniconda\install\envs\mubai\lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 2048 into shape (0)

**Comment by xszyou** [comment]
扬声器当麦克风了吧

**Comment by Solenyalyl** [comment]
我将miniconda换成了anaconda，然后就可以了

**Comment by wangyule0** [comment]
问一下numpy版本改成啥了，我也遇到了相同的问题
@Solenyalyl

**Comment by Solenyalyl** [comment]
1.26.4

**Comment by lovegit2021** [comment]
我也遇到同样的问题，ue5中左上角可以显示出回复文字，但是数字人没有反应，而且fay环境中的numpy==1.26.4，还是存在这个问题

**Comment by Solenyalyl** [comment]
anaconda改了吗？
