### ISSUE TITLE
启动funasr时报错，python3.9

### ISSUE THREAD

**Issue by yjyz1011** [xszyou/Fay#112]
启动funasr时报错，python3.9，该如何处理？
(D:\RUN_FOLDER\FAY\paystu) D:\RUN_FOLDER\FAY\Fay-fay-assistant-edition-latest\Fay-fay-assistant-edition\test\funasr>python -u ASR_server.py --host "0.0.0.0" --port 10197 --ngpu 0
Notice: ffmpeg is not installed. torchaudio is used to load audio
If you want to use ffmpeg backend to load audio, please install it by:
        sudo apt install ffmpeg # ubuntu
        # brew install ffmpeg # mac
d:\run_folder\fay\fay-fay-assistant-edition-latest\fay-fay-assistant-edition\test\funasr\funasr-main\funasr\datasets\large_datasets\utils\tokenize.py:91: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if vad is not -2:
model loading
2024-04-25 19:22:28,645 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-04-25 19:22:28,647 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-04-25 19:22:28,896 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 654b3c9a392aa9eba0ffbc1da3b0c0de and a total number of 976 components indexed
2024-04-25 19:22:30,015 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: C:\Users\Administrator\.cache\modelscope\hub\iic\speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch\model.pt
2024-04-25 19:22:42,781 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: C:\Users\Administrator\.cache\modelscope\hub\iic\speech_fsmn_vad_zh-cn-16k-common-pytorch\model.pt
2024-04-25 19:22:43,735 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: C:\Users\Administrator\.cache\modelscope\hub\iic\punc_ct-transformer_zh-cn-common-vocab272727-pytorch\model.pt
model loaded
Traceback (most recent call last):
  File "D:\RUN_FOLDER\FAY\Fay-fay-assistant-edition-latest\Fay-fay-assistant-edition\test\funasr\ASR_server.py", line 79, in <module>
    asyncio.run(main())
  File "D:\RUN_FOLDER\FAY\paystu\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\RUN_FOLDER\FAY\paystu\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\RUN_FOLDER\FAY\Fay-fay-assistant-edition-latest\Fay-fay-assistant-edition\test\funasr\ASR_server.py", line 76, in main
    await worker_task
  File "D:\RUN_FOLDER\FAY\Fay-fay-assistant-edition-latest\Fay-fay-assistant-edition\test\funasr\ASR_server.py", line 52, in worker
    websocket, url = await task_queue.get()
  File "D:\RUN_FOLDER\FAY\paystu\lib\asyncio\queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-4' coro=<worker() running at D:\RUN_FOLDER\FAY\Fay-fay-assistant-edition-latest\Fay-fay-assistant-edition\test\funasr\ASR_server.py:52> cb=[<TaskWakeupMethWrapper object at 0x000001EF5C1AA0D0>()]> got Future <Future pending> attached to a different loop

**Comment by yangtao-manoo** [comment]
遇到同样的错误，不知道你解决了没有

**Comment by sendtion** [comment]
我也是，需要先安装ffmpeg吗
