### ISSUE TITLE
window11下Pycharm运行fay_booter.py文件报错

### ISSUE THREAD

**Issue by onex7777** [xszyou/Fay#122]
pygame 2.1.3 (SDL 2.0.22, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
[20:21:28][系统] 开启服务...
[20:21:28][系统] 读取配置...
[20:21:28][系统] 开启核心服务...
[20:21:29][系统] TTS 服务已经连接！
[20:21:29][系统] 开启远程设备音频输入服务...
[20:21:29][系统] 开启agent服务...
[20:21:29][系统] 注册命令...
[20:21:29][系统] 完成!
[20:21:29][系统] 使用 'help' 获取帮助.
help
[20:22:21][系统] in <msg> 	通过控制台交互
[20:22:21][系统] restart 	重启服务
[20:22:21][系统] stop 		关闭服务
in 你好！
[20:22:30][控制台] 控制台: 你好！
Exception in thread Thread-14 (console_listener):
Traceback (most recent call last):
  File "D:\Python\Miniconda\envs\agent\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\Python\Miniconda\envs\agent\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python\Pingan\LLM\Fay-fay-agent-edition\fay_booter.py", line 166, in console_listener
    util.printInfo(3, "控制台", '{}: {}'.format('控制台', msg))
  File "D:\Python\Pingan\LLM\Fay-fay-agent-edition\utils\util.py", line 36, in printInfo
    wsa_server.get_web_instance().add_cmd({"panelMsg": text})
AttributeError: 'NoneType' object has no attribute 'add_cmd'

**Comment by xszyou** [comment]
请更换vs code测试
