### ISSUE TITLE
最新助理版按照文档执行安装都没问题，但是启动main.py报错

### ISSUE THREAD

**Issue by joely110** [xszyou/Fay#132]
Traceback (most recent call last):
  File "D:\fay\fay-assistant-edition\main.py", line 8, in <module>
    from gui import flask_server
  File "D:\fay\fay-assistant-edition\gui\flask_server.py", line 9, in <module>
    import fay_booter
  File "D:\fay\fay-assistant-edition\fay_booter.py", line 7, in <module>
    from core.fay_core import FeiFei
  File "D:\fay\fay-assistant-edition\core\fay_core.py", line 17, in <module>
    from utils import util, storer, config_util
ImportError: cannot import name 'storer' from 'utils' (unknown location)

**Comment by wxthu** [comment]
这些代码感觉都跑不起来，只是搭好了一些接口而已
