### ISSUE TITLE
MacOS[M3] 安装出错，求助

### ISSUE THREAD

**Issue by siriuslan** [xszyou/Fay#136]
我试过Python 3.10 和 3.12，都是以下的错误

`Collecting gevent~=22.10.1 (from -r requirements.txt (line 17))
  Using cached gevent-22.10.2.tar.gz (6.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      performance hint: src/gevent/libev/corecext.pyx:1339:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types

      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------

      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Traceback (most recent call last):
        File "/Users/binglan/projects/study/Fay/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/binglan/projects/study/Fay/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/binglan/projects/study/Fay/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-build-env-8l7z_fcx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-build-env-8l7z_fcx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-build-env-8l7z_fcx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-install-r_s6d15y/gevent_ba353187c52c4714b73b96e7e3a5a2de/_setuputils.py", line 237, in cythonize1
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-build-env-8l7z_fcx/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/2v/c21_ttv501db32vlb4k6lgtm0000gn/T/pip-build-env-8l7z_fcx/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by siriuslan** [comment]
已解决，gevent使用最新版24.11.1即可
