### ISSUE TITLE
启动main.py报错

### ISSUE THREAD

**Issue by zhang0135789** [xszyou/Fay#39]
```
(base) zz@ubuntu:~/app/python/Fay$ python main.py 
pygame 2.1.3 (SDL 2.0.22, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/zz/software/conda/anaconda3/lib/python3.9/site-packages/revChatGPT/__init__.py:29: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  __import__("warnings").warn(
Traceback (most recent call last):
  File "/home/zz/app/python/Fay/main.py", line 11, in <module>
    from gui.window import MainWindow
  File "/home/zz/app/python/Fay/gui/window.py", line 8, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2: symbol krb5_ser_context_init version krb5_3_MIT not defined in file libkrb5.so.3 with link time reference

```

**Comment by zhouxiaofeng-zxf** [comment]
我也遇到这个问题了

**Comment by feipengheart** [comment]
请问这个问题解决了吗，在linux环境我也遇到这个问题，是不是必须要在windows系统下运行啊

**Comment by Dinomancer** [comment]
linux我也不行，windows上很容易就装上了

**Comment by Gartinez** [comment]
解决了吗 我Linux上前一天正常 第二天启动不了了
