### ISSUE TITLE
使用本地funasr报错

### ISSUE THREAD

**Issue by Solenyalyl** [xszyou/Fay#97]
在运行python -u ASR_server.py --host "0.0.0.0" --port 10197 --ngpu 0 --model ./data/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404时，报错：
2024-01-07 16:01:29,003 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-01-07 16:01:29,003 - modelscope - INFO - Loading ast index from C:\Users\solenya\.cache\modelscope\ast_indexer
2024-01-07 16:01:29,145 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 ffea442fdc1827da91e49464a349124a and a total number of 946 components indexed
model loading
Traceback (most recent call last):
  File "C:\mubai\Fay-fay-assistant-edition\Fay-fay-assistant-edition\test\funasr\ASR_server.py", line 59, in <module>
    inference_pipeline_asr = pipeline(
  File "C:\setup\miniconda\install\envs\mubai\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\setup\miniconda\install\envs\mubai\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\setup\miniconda\install\envs\mubai\lib\site-packages\modelscope\utils\registry.py", line 206, in build_from_cfg
    raise TypeError(
TypeError: type must be a str or valid type, but got <class 'NoneType'>

请问是什么原因，该如何解决？
感谢~~

**Comment by qinzhuguang** [comment]
没有下载模型

**Comment by Solenyalyl** [comment]
![image](https://github.com/TheRamU/Fay/assets/33305699/af61fc85-e9bd-401b-8de9-c9e637ad6262)
是这个吗？已经下载并且安装了

**Comment by qinzhuguang** [comment]
> ![image](https://private-user-images.githubusercontent.com/33305699/294808950-af61fc85-e9bd-401b-8de9-c9e637ad6262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODkyMzYsIm5iZiI6MTcwNDk4ODkzNiwicGF0aCI6Ii8zMzMwNTY5OS8yOTQ4MDg5NTAtYWY2MWZjODUtZTliZC00MDFiLThkZTktYzllNjM3YWQ2MjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmY2Q0MDE3NjI0M2FkMGI3YTlmNzRmMWQyODc0ZmVkYmNiYWExZjNhM2I5MGM5YTZiZjkzM2FhZmY2MDFlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLTsXbaCAidAWb47FlcwiR3PA2xdREXpXTuIETcBQGE) 是这个吗？已经下载并且安装了

对

**Comment by LauraGPT** [comment]
Solution: https://github.com/alibaba-damo-academy/FunASR/discussions/1319

**Comment by Solenyalyl** [comment]
这个问题最后解决了，我的问题比较智障，是因为解压之后，文件夹下面又套了一个文件夹，所以python -u ASR_server.py --host "0.0.0.0" --port 10197 --ngpu 0 --model ./data/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
